Sqlg Documentation
==================
Pieter Martin
v1.3.3, December 2016:

*Sqlg* is a implementation of 'http://tinkerpop.apache.org/[Apache TinkerPop]' on a 'http://en.wikipedia.org/wiki/Relational_database_management_system[RDBMS]'.
Currently 'http://www.postgresql.org/[Postgresql]', 'http://hsqldb.org/[HSQLDB]', and 'http://h2database.com[H2 database]' are supported.

== Introduction

Sqlg primary challenge is to reduce latency by combining TinkerPop 'http://tinkerpop.apache.org/docs/current/reference/#graph-traversal-steps[steps]'
into as few as possible database calls. The fine grained nature of graph traversals makes this crucial else the remote
call latency has a severe performance impact.

Additionally for Postgresql Sqlg supports various bulk modes to reduce latency when modifying the graph.

[NOTE]
Hsqldb and H2 do not suffer the same latency as Postgresql as it runs embedded in the jvm.

=== TinkerPop supported features

Sqlg version 1.3.3 runs on TinkerPop 3.2.3

Sqlg passes TinkerPop's `StructureStandardSuite` and `ProcessStandardSuite` test suites.

Graph Features **not** implemented.

* Computer
* ThreadedTransactions
* Variables

Vertex Features **not** implemented.

* MultiProperties
* MetaProperties
* UserSuppliedIds
* NumericIds
* StringIds
* UuidIds
* CustomIds
* AnyIds

Edge Features **not** implemented.

* UserSuppliedIds
* NumericIds
* StringIds
* UuidIds
* CustomIds
* AnyIds

Vertex property features **not** implemented.

* AddProperty
* RemoveProperty
* UserSuppliedIds
* NumericIds
* StringIds
* UuidIds
* CustomIds
* AnyIds
* MapValues
* MixedListValues
* SerializableValues
* UniformListValues

Edge property feature **not** implemented.

* MapValues
* MixedListValues
* SerializableValues
* UniformListValues

